-- Création des tables pour la gestion des fournisseurs, articles, bons de commande et compositions

CREATE TABLE FOURNISSEUR (
    ID INT PRIMARY KEY,
    NOM VARCHAR(100)
);

CREATE TABLE ARTICLE (
    ID INT PRIMARY KEY,
    REF VARCHAR(50),
    DESIGNATION VARCHAR(255),
    PRIX DECIMAL(10,2),
    ID_FOU INT,
    FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
);

CREATE TABLE BON (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO VARCHAR(50),
    DATE_CMDE DATE,
    DELAI INT,
    ID_FOU INT,
    FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
);

CREATE TABLE COMPO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    QTE INT,
    ID_ART INT,
    ID_BON INT,
    FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID),
    FOREIGN KEY (ID_BON) REFERENCES BON(ID)
);