
USE compta2;

SELECT * FROM ARTICLE;

SELECT REF, DESIGNATION
FROM ARTICLE
WHERE PRIX > 2;

SELECT *
FROM ARTICLE
WHERE PRIX >= 2 AND PRIX <= 6.25;

SELECT *
FROM ARTICLE
WHERE PRIX BETWEEN 2 AND 6.25;

SELECT A.*
FROM ARTICLE A
JOIN FOURNISSEUR F ON A.ID_FOU = F.ID
WHERE (PRIX NOT BETWEEN 2 AND 6.25)
  AND F.NOM = 'Française d''Imports'
ORDER BY PRIX DESC;

SELECT A.*
FROM ARTICLE A
JOIN FOURNISSEUR F ON A.ID_FOU = F.ID
WHERE F.NOM = 'Française d''Imports' OR F.NOM = 'Dubois & Fils';

SELECT A.*
FROM ARTICLE A
JOIN FOURNISSEUR F ON A.ID_FOU = F.ID
WHERE F.NOM IN ('Française d''Imports', 'Dubois & Fils');

SELECT A.*
FROM ARTICLE A
JOIN FOURNISSEUR F ON A.ID_FOU = F.ID
WHERE F.NOM NOT IN ('Française d''Imports', 'Dubois & Fils');

SELECT *
FROM BON
WHERE datetime BETWEEN '2019-02-01' AND '2019-04-30';
